update workflows
tidyverse/readxl pull request #655
Opened 2021-07-26 22:42 UTC by sbearrows

Unsure if there are changes we need to make for the readxl workflow @jimhester 

fixes #649

2021-07-27 12:52 UTC, jimhester commented on .github/workflows/pkgdown.yaml
> -          remotes::install_cran("devtools")
We need to add these packages to the `DESCRIPTION` file in the `Config/Needs/website` field. e.g.

```
Config/Needs/website: tidyverse/tidytemplate, tidyverse, devtools
```

2021-07-27 12:55 UTC, jimhester commented on .github/workflows/test-coverage.yaml
> -        run: covr::codecov(line_exclusions = c("src/xls.c", "src/xlstool.c", "src/rapidxml.h", "src/rapidxml_print.h", "src/endian.c", "src/ole.c", "src/libxls/brdb.h"))
Instead of specifying these files here I would suggest you use a `.covrignore` file. The contents are regular expressions, similar to `.Rbuildignore`. This would allow them to be picked up by covr locally, and avoids needing customization in the workflows.

The contents of `.covrignore` would be something like the following.

```
src/xls\.c
src/xlstool\.c
src/rapidxml.*
src/endian\.c
src/ole\.c
src/libxls/brdb\.h
```

2021-07-27 12:56 UTC, jimhester commented on README.Rmd
> +[![R-CMD-check](https://github.com/tidyverse/readxl/workflows/R-CMD-check/badge.svg)](https://github.com/tidyverse/readxl/actions)
You should delete line 19 and replace it with this line

2021-07-27 12:57 UTC, jimhester requested changes
The workflows themselves don't need changes, but there are some other files we should add information to, I left comments inline

2021-07-27 15:18 UTC, jennybc commented on .github/workflows/pkgdown.yaml
> -          remotes::install_cran("devtools")
I was using the dev version of pkgdown for some reason, but until/unless we re-discover that need, we can let that go.

2021-07-27 15:21 UTC, jennybc commented on README.Rmd
> +[![R-CMD-check](https://github.com/tidyverse/readxl/workflows/R-CMD-check/badge.svg)](https://github.com/tidyverse/readxl/actions)
It would be good to also rebuild the README with `devtools::build_readme()`. Depending on how you made your local repo, there might be a git hook that actually "encourages" (= forces) you to do this.

2021-07-28 00:45 UTC, jennybc commented
I made one more commit to adapt this to the file layout adopted when we merged #653.

Thanks!

2021-07-28 00:45 UTC, merged

2021-07-28 13:23 UTC, jimhester commented on .covrignore
> +src/rapidxml_print.h
These should not be here, they are interpreted as regular expressions (e.g. so the `.` will match any character) and are already covered by the cases further down.

2021-07-28 13:25 UTC, jimhester commented on .covrignore
> +src/rapidxml_print.h
But I think with the current master we can just ignore the directory completely (which is what is done anyway), so this comment can be ignored, sorry for the noise 🙉

2021-07-28 16:24 UTC, sbearrows commented on .covrignore
> +src/rapidxml_print.h
You're right, I had first started adding them by hand when I realized what you were asking for. I forgot to remove them before pushing. Thank you for the noise!👂🏻